package com.phform.server.entity;

// default package

/**
 * FormTextArea generated by MyEclipse Persistence Tools
 */

public class FormTextArea implements java.io.Serializable
{
    
    // Fields
    
    private String id;
    
    private String instanceId;
    
    private String textareaId;
    
    private Long version;
    
    private String textareaValue;
    
    // Property accessors
    
    public String getId()
    {
        return this.id;
    }
    
    public void setId(String id)
    {
        this.id = id;
    }
    
    public String getInstanceId()
    {
        return this.instanceId == null ? "" : instanceId.trim();
    }
    
    public void setInstanceId(String instanceId)
    {
        this.instanceId = instanceId;
    }
    
    public String getTextareaId()
    {
        return this.textareaId == null ? "" : textareaId.trim();
    }
    
    public void setTextareaId(String textareaId)
    {
        this.textareaId = textareaId;
    }
    
    public Long getVersion()
    {
        return this.version;
    }
    
    public void setVersion(Long version)
    {
        this.version = version;
    }
    
    public String getTextareaValue()
    {
        return this.textareaValue == null ? "" : textareaValue.trim();
    }
    
    public void setTextareaValue(String textareaValue)
    {
        this.textareaValue = textareaValue;
    }
}