package com.phform.server.entity;

// default package

/**
 * FormInstance generated by MyEclipse Persistence Tools
 */

public class FormInstance implements java.io.Serializable
{
    
    // Fields
    
    private String id;
    
    private String formId;
    
    private Long version;
    
    // Property accessors
    
    public Long getVersion()
    {
        return version;
    }
    
    public void setVersion(Long version)
    {
        this.version = version;
    }
    
    public String getId()
    {
        return this.id == null ? "" : id.trim();
    }
    
    public void setId(String id)
    {
        this.id = id;
    }
    
    public String getFormId()
    {
        return this.formId == null ? "" : formId.trim();
    }
    
    public void setFormId(String formId)
    {
        this.formId = formId;
    }
    
}