package com.phform.server.entity;

// default package

/**
 * FormCheckbox generated by MyEclipse Persistence Tools
 */

public class FormCheckbox implements java.io.Serializable
{
    
    // Fields
    
    private String id;
    
    private String instanceId;
    
    private String checkboxId;
    
    private Long version;
    
    private String checkboxValue;
    
    // Property accessors
    
    public String getId()
    {
        return this.id;
    }
    
    public void setId(String id)
    {
        this.id = id;
    }
    
    public String getInstanceId()
    {
        return this.instanceId == null ? "" : instanceId.trim();
    }
    
    public void setInstanceId(String instanceId)
    {
        this.instanceId = instanceId;
    }
    
    public String getCheckboxId()
    {
        return this.checkboxId == null ? "" : checkboxId.trim();
    }
    
    public void setCheckboxId(String checkboxId)
    {
        this.checkboxId = checkboxId;
    }
    
    public Long getVersion()
    {
        return this.version;
    }
    
    public void setVersion(Long version)
    {
        this.version = version;
    }
    
    public String getCheckboxValue()
    {
        return this.checkboxValue == null ? "" : checkboxValue.trim();
    }
    
    public void setCheckboxValue(String checkboxValue)
    {
        this.checkboxValue = checkboxValue;
    }
}