package com.phform.server.entity;

// default package

/**
 * FormText generated by MyEclipse Persistence Tools
 */

public class FormText implements java.io.Serializable
{
    
    // Fields
    
    private String id;
    
    private String instanceId;
    
    private String textId;
    
    private Long version;
    
    private String textValue;
    
    // Property accessors
    
    public String getId()
    {
        return this.id;
    }
    
    public void setId(String id)
    {
        this.id = id;
    }
    
    public String getInstanceId()
    {
        return this.instanceId == null ? "" : instanceId.trim();
    }
    
    public void setInstanceId(String instanceId)
    {
        this.instanceId = instanceId;
    }
    
    public String getTextId()
    {
        return this.textId == null ? "" : textId.trim();
    }
    
    public void setTextId(String textId)
    {
        this.textId = textId;
    }
    
    public Long getVersion()
    {
        return this.version;
    }
    
    public void setVersion(Long version)
    {
        this.version = version;
    }
    
    public String getTextValue()
    {
        return this.textValue == null ? "" : textValue.trim();
    }
    
    public void setTextValue(String textValue)
    {
        this.textValue = textValue;
    }
    
}